# Generated by Django 4.0.3 on 2022-04-10 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=26)),
                ('level', models.IntegerField(default=1)),
                ('attributes', models.JSONField(default=dict)),
                ('equipment', models.JSONField(default=dict)),
                ('inventory', models.JSONField(default=list)),
                ('location', models.JSONField(default=dict)),
                ('activity', models.JSONField(default=dict)),
                ('currency', models.JSONField(default=dict)),
                ('flags', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('size', models.IntegerField(default=0)),
                ('population', models.IntegerField(default=0)),
                ('flags', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Kingdom',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('population', models.IntegerField(default=0)),
                ('land', models.JSONField(default=dict)),
                ('flags', models.JSONField(default=dict)),
                ('ruler', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='innkeeper.character')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=26)),
                ('settings', models.JSONField()),
                ('flags', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('size', models.IntegerField(default=0)),
                ('population', models.IntegerField(default=0)),
                ('owner', models.CharField(blank=True, max_length=32)),
                ('flags', models.JSONField(default=dict)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innkeeper.continent')),
                ('kingdom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='innkeeper.kingdom')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='innkeeper.player'),
        ),
    ]
